<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="flask_tests.TestWebApp-20220307120141" tests="3" file="flask_tests.py" time="0.004" timestamp="2022-03-07T12:01:42" failures="0" errors="1" skipped="0">
	<testcase classname="flask_tests.TestWebApp" name="test_app" time="0.001" timestamp="2022-03-07T12:01:42"/>
	<testcase classname="flask_tests.TestWebApp" name="test_hello" time="0.001" timestamp="2022-03-07T12:01:42"/>
	<testcase classname="flask_tests.TestWebApp" name="test_register_user" time="0.002" timestamp="2022-03-07T12:01:42">
		<error type="AttributeError" message="'TestWebApp' object has no attribute 'client'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "c:\users\johnny\desktop\everything\school\cs 4800 software engineering\bronco-mates\src\unittest\python\flask_tests.py", line 25, in test_register_user
    response = self.client.post(url_for("accountSettings"), data={
AttributeError: 'TestWebApp' object has no attribute 'client'
]]></error>
	</testcase>
</testsuite>
