<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="app_tests.HelloWorldTest-20220225182234" tests="1" file="app_tests.py" time="0.002" timestamp="2022-02-25T18:22:35" failures="0" errors="1" skipped="0">
	<testcase classname="app_tests.HelloWorldTest" name="test_should_issue_hello_world_message" time="0.002" timestamp="2022-02-25T18:22:35">
		<error type="NameError" message="name 'app' is not defined"><![CDATA[Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "c:\users\johnny\desktop\everything\school\cs 4800 software engineering\bronco-mates\src\unittest\python\app_tests.py", line 10, in test_should_issue_hello_world_message
    app(out)
NameError: name 'app' is not defined
]]></error>
	</testcase>
</testsuite>
