<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="flask_tests.flaskTests-20220307113730" tests="2" file="flask_tests.py" time="0.003" timestamp="2022-03-07T11:37:31" failures="0" errors="1" skipped="0">
	<testcase classname="flask_tests.flaskTests" name="testingUnittests" time="0.001" timestamp="2022-03-07T11:37:31"/>
	<testcase classname="flask_tests.flaskTests" name="testRedirect" time="0.002" timestamp="2022-03-07T11:37:31">
		<error type="AttributeError" message="'flaskTests' object has no attribute 'get'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "c:\users\johnny\desktop\everything\school\cs 4800 software engineering\bronco-mates\src\unittest\python\flask_tests.py", line 8, in testRedirect
    response = self.get("/hello")
AttributeError: 'flaskTests' object has no attribute 'get'
]]></error>
	</testcase>
</testsuite>
