<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="flask_tests.AppTestCase-20220307123207" tests="2" file="flask_tests.py" time="0.004" timestamp="2022-03-07T12:32:08" failures="1" errors="0" skipped="0">
	<testcase classname="flask_tests.AppTestCase" name="test" time="0.001" timestamp="2022-03-07T12:32:08"/>
	<testcase classname="flask_tests.AppTestCase" name="test_accountSettings" time="0.003" timestamp="2022-03-07T12:32:08">
		<failure type="AssertionError" message=""><![CDATA[Traceback (most recent call last):
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\Johnny\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "c:\users\johnny\desktop\everything\school\cs 4800 software engineering\bronco-mates\src\unittest\python\flask_tests.py", line 18, in test_accountSettings
    assert response.status_code == 200
AssertionError
]]></failure>
	</testcase>
</testsuite>
